spring:
  datasource:
    url: jdbc:postgresql://localhost:5228/bons-service
    username: bons-service
    password: bons-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false