spring:
  datasource:
    url: jdbc:postgresql://localhost:5227/colis-service
    username: colis-service
    password: colis-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false