server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isMeAyoub/tawsal-express-configurations.git
          search-paths: configurations
          default-label: main
          username: isMeAyoub
          password: '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'
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

encrypt:
  key: 'NhU1ULi?cVyNP%+EM@,V4RbEusXYSlpy'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
