spring:
  datasource:
    url: jdbc:postgresql://localhost:5224/facturation-service
    username: facturation-service
    password: facturation-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false